package com.store.store_app.models;

public enum PermissionEnum {
    CREATE_PRODUCTS,
    READ_PRODUCTS,
    UPDATE_PRODUCTS,
    DELETE_PRODUCTS,
    CREATE_CATEGORY,
    READ_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    CREATE_USER_ADMIN,
    CREATE_USER,
    READ_USER_ADMIN,
    READ_USER,
    UPDATE_USER,
    DELETE_USER,
    CREATE_ORDER,
    READ_ORDER,
    DELETE_ORDER,
    CREATE_ORDERDETAILS,
    READ_ORDERDETAILS,
    DELETE_ORDERDETAILS,
    CREATE_ROLE,
    READ_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    CREATE_PERMISSION,
    READ_PERMISSION

}
